name: Docker Image CI

on:
#  release:
#    types: [published]
  
  # Triggers the workflow on push or pull request events but only for the master branch
#  push:
#    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      DOCKER_TAG_VERSION: 'latest'

    steps:
    - uses: actions/checkout@v2
    -
      name: Get Docker Image Tag version from Git tag
      run: echo "$GITHUB_REF" | cut -d '/' -f3 | sed -e 's/^v//g' >> STORE_TAG_VERSION
    -
      name: Set Docker Image Version (if existent)
      run: if [ -z "$STORE_TAG_VERSION" ]; then echo "$STORE_TAG_VERSION" >> DOCKER_TAG_VERSION; fi
      
    - 
      name: Print Docker Image Tag
      run: echo "traeger/codabix:$DOCKER_TAG_VERSION"
        
    - 
      name: Build the x64 Docker image
      run: cp -r scripts x64/ && cd x64 && docker build . --file Dockerfile --tag traeger/codabix:$DOCKER_TAG_VERSION
      
    - 
      name: Build the RPi Docker image
      run: cp -r scripts rpi/ && cd rpi && docker build . --file Dockerfile --tag traeger/codabix:rpi-$DOCKER_TAG_VERSION
