name: Docker Image CI

on:
#  release:
#    types: [published]
  
  # Triggers the workflow on push or pull request events but only for the master branch
#  push:
#    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      DOCKER_TAG_VERSION: 'latest'

    steps:
    - uses: actions/checkout@v2
    -
      name: Get Docker Image Tag version from Git tag
      run: echo "$GITHUB_REF" | cut -d '/' -f3 | sed -e 's/^v//g' >> STORE_TAG_VERSION
    -
      name: Set Docker Image Version (if existent)
      id: tags
      run: |
        if [ -z "$STORE_TAG_VERSION" ]; then echo "$STORE_TAG_VERSION" >> DOCKER_TAG_VERSION; fi
        echo ::set-output name=tags::traeger/codabix:${DOCKER_TAG_VERSION}
      
    - 
      name: Print Docker Image Tag
      run: echo "traeger/codabix:$DOCKER_TAG_VERSION"
      
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@master
      with:
          platforms: linux/amd64
  
    -
      name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@master

    -
      name: Build
      uses: docker/build-push-action@v2
      with:
        builder: ${{ steps.buildx.outputs.name }}
        context: .
        file: ./Dockerfile
        platforms: linux/amd64
        push: false
        tags: ${{ steps.tags.outputs.tags }}
